include:
  - wazuh/docker-compose.yml

services:
  offer-ssh:
    build: ./offer-ssh
    image: logghantering/offer-ssh:4.14.4
    hostname: offer-ssh
    restart: unless-stopped
    ports:
      - "2222:22"
    depends_on:
      - wazuh.manager

  offer-juice-shop:
    build: ./offer-juice-shop
    image: logghantering/offer-juice-shop:4.14.4
    hostname: offer-juice-shop
    restart: unless-stopped
    expose:
      - "3000"
    depends_on:
      - wazuh.manager

  nginx-proxy:
    build: ./nginx-proxy
    image: logghantering/nginx-proxy:4.14.4
    hostname: nginx-proxy
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - wazuh.manager
      - offer-juice-shop

  flog-noise:
    build: ./flog-noise
    image: logghantering/flog-noise:4.14.4
    hostname: flog-noise
    restart: unless-stopped
    depends_on:
      - wazuh.manager
